import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { AllCharacters } from '../models/mortyModel';
import { dehydrate, QueryClient, useQuery } from 'react-query';
import Characters from '../components/Characters';

export default function Home({
    initialMorty,
}: {
    initialMorty: AllCharacters;
}) {
    const { data } = useQuery('morty', getMorty, {
        initialData: initialMorty,
        refetchOnMount: false,
        refetchOnWindowFocus: false,
    });
    console.log('🚀 ~ file: index.tsx:17 ~ data:', data);
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    content="Generated by create next app"
                    name="description"
                />
                <meta
                    content="width=device-width, initial-scale=1"
                    name="viewport"
                />
                <link href="/favicon.ico" rel="icon" />
            </Head>
            <main className={styles.main}>
                <Characters />
            </main>
        </>
    );
}

const getMorty = (): Promise<AllCharacters> =>
    fetch('https://rickandmortyapi.com/api/character').then(res => res.json());

export async function getServerSideProps() {
    const queryClient = new QueryClient();
    await queryClient.prefetchQuery('morty', getMorty);
    return {
        props: {
            dehydratedState: dehydrate(queryClient),
        },
    };
}
