import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { AllCharacters } from "../models/mortyModel";
import { useQuery, QueryClient, dehydrate } from "react-query";
import { Text } from "@chakra-ui/react";
import Characters from "../components/Characters";
const inter = Inter({ subsets: ["latin"] });

export default function Home({
  initialMorty,
}: {
  initialMorty: AllCharacters;
}) {
  const { data } = useQuery("morty", getMorty, {
    initialData: initialMorty,
    refetchOnMount: false,
    refetchOnWindowFocus: false,
  });
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Characters />
      </main>
    </>
  );
}

const getMorty = (): Promise<AllCharacters> =>
  fetch("https://rickandmortyapi.com/api/character").then((res) => res.json());

export async function getServerSideProps() {
  const queryClient = new QueryClient();
  await queryClient.prefetchQuery("morty", getMorty);
  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  };
}
